# Generated by Django 4.1.3 on 2025-10-01 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField()),
                ('tipo', models.CharField(choices=[('ESTRENO', 'Estreno'), ('CAMBIO_FUNCION', 'Cambio Funcion'), ('RECOMENDACION', 'Recomendacion')], max_length=30)),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('LEIDA', 'Leida')], default='ENVIADA', max_length=20)),
                ('titulo_mensaje', models.CharField(max_length=100)),
                ('cuerpo_mensaje', models.TextField()),
                ('enlace_mensaje', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('usuario_id', models.UUIDField(primary_key=True, serialize=False)),
                ('generos_json', models.JSONField(default=list)),
                ('calle_preferida', models.CharField(blank=True, max_length=255)),
                ('distrito_preferida', models.CharField(blank=True, max_length=100)),
                ('latitud_preferida', models.FloatField(blank=True, null=True)),
                ('longitud_preferida', models.FloatField(blank=True, null=True)),
                ('frecuencia_notif', models.CharField(choices=[('DIARIA', 'DIARIA'), ('SEMANAL', 'SEMANAL')], default='SEMANAL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionPersonalizada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obra_id', models.UUIDField()),
                ('score_relevancia', models.FloatField()),
                ('razon', models.TextField(blank=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='notifications.notificacion')),
            ],
        ),
    ]
