# Generated by Django 4.1.3 on 2025-10-01 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadCache',
            fields=[
                ('funcion_id', models.UUIDField(primary_key=True, serialize=False)),
                ('total_asientos', models.IntegerField()),
                ('disponibles', models.IntegerField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField()),
                ('funcion_id', models.UUIDField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('codigo_qr', models.CharField(blank=True, max_length=255)),
                ('detalles_ticket', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asiento', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tickets.reserva')),
            ],
        ),
    ]
