# Generated by Django 4.1.3 on 2025-10-01 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('DRAMA', 'Drama'), ('COMEDIA', 'Comedia'), ('MUSICAL', 'Musical'), ('EXPERIMENTAL', 'Experimental')], max_length=20)),
                ('director_nombre', models.CharField(max_length=255)),
                ('director_rol', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director')], default='DIRECTOR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('calle', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director')], max_length=20)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='content.obra')),
            ],
        ),
        migrations.AddField(
            model_name='obra',
            name='teatro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='content.teatro'),
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField()),
                ('disponibilidad_asientos', models.IntegerField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='content.obra')),
            ],
        ),
    ]
