# Generated by Django 4.1.3 on 2025-10-01 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('genero_filtro', models.CharField(blank=True, choices=[('DRAMA', 'Drama'), ('COMEDIA', 'Comedia'), ('MUSICAL', 'Musical'), ('EXPERIMENTAL', 'Experimental')], max_length=20)),
                ('calle_filtro', models.CharField(blank=True, max_length=255)),
                ('distrito_filtro', models.CharField(blank=True, max_length=100)),
                ('latitud_filtro', models.FloatField(blank=True, null=True)),
                ('longitud_filtro', models.FloatField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObraVistaCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('DRAMA', 'Drama'), ('COMEDIA', 'Comedia'), ('MUSICAL', 'Musical'), ('EXPERIMENTAL', 'Experimental')], max_length=20)),
                ('calle', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('funciones_json', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntuacion', models.FloatField()),
                ('razon', models.TextField(blank=True)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='discovery.busqueda')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='discovery.obravistacache')),
            ],
        ),
    ]
